### ISSUE TITLE
Replace occurrences of "Atomic CSS" with "ACSS" and more...

### ISSUE THREAD

**Issue by thierryk** [acss-io/acss-site#117]
@johnpolacek pointed out to me that the name of this project seems to be "Atomic CSS" since we have `<h1>Atomic CSS</h1>` on our landing page as well as in our `#header`.

Now that there are many flavors of Atomic CSS libraries out there I think it is important to make sure people differentiate "Atomic CSS" (the architecture) from Atomizer (the tool and its related syntax).

To avoid this problem, I'd like to replace "Atomic CSS" in `#header` with **ACSS** (something I personally used a lot when referencing our project). And replace "Atomic CSS" in the `h1` with **Atomic CSS on steroids**, or **Dynamic Atomic CSS library**, or something similar.

@src-code @redonkulus @renatoi @pankajparashar What do you guys think? If you agree with the idea then I'll submit a PR to fix these occurrences throughout the site (leaving alone "Atomic CSS" whenever it refers to the architecture, but replacing it with "ACSS" when it refers to the project itself).

**Comment by src-code** [comment]
I'm not sure this would help alleviate confusion between Atomizer and Atomic CSS (a problem we've always grappled with since the beginning of this project), because to me ACSS != Atomizer any more than Atomic CSS does.  ACSS sounds like it'd just be branding then for Atomizer's particular flavor of Atomic CSS?  If that's the case, I think we'd need to do more than just update the headers to make all this clear.

**Comment by thierryk** [comment]
> ACSS sounds like it'd just be branding then for Atomizer's particular flavor of Atomic CSS?

Yes, ACSS would be exactly that. It's Atomic CSS via Atomizer. Atomic CSS is a architecture, ACSS is a "flavor" of the many implementations we can now find in the wild&mdash;and that includes the approach Yahoo! Mail is taking.

As @johnpolacek says, the title on https://acss.io suggests that Atomic CSS is whatever people see on that site. Ironically, people could think that "Atomic CSS" is a way (via Atomizer) to do "Functional CSS" and that's plain crazy if you ask me.

**Comment by thierryk** [comment]
This [reply](https://medium.com/@simonswiss/i-had-heard-of-it-a-few-times-and-just-had-a-proper-look-after-seeing-your-comment-dde5f6a8a58c#.h4czpv8v3) I received on Medium shows the issue perfectly:

> I personally prefer the naming convention of tachyons, but “atomic CSS” sure sounds like a good alternative!

Here, Simon does not use the term "Atomic CSS" to refer to the architecture but to refer to our project&mdash;which is wrong.

**Comment by thierryk** [comment]
Coming back to this :)
ACSS could stand for *Atomized* CSS rather than Atomic CSS; that way we have our reference to Atomizer. 
I must say that "*Dynamic Atomic CSS library*" may be better (than Atomic CSS) for people landing on the home page as it mentions the big difference with other libraries out there.

Should I create a PR or do you guys prefer to leave things the way they are?

**Comment by thierryk** [comment]
A more recent example of the "problem":

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">When you say atomic css are you referring to <a href="https://t.co/VHj9Rjbj4D">https://t.co/VHj9Rjbj4D</a>?</p>&mdash; Joe Badaczewski 🏂 (@joe307bad) <a href="https://twitter.com/joe307bad/status/1259083489170919424?ref_src=twsrc%5Etfw">May 9, 2020</a></blockquote>

**Comment by thierryk** [comment]
I think I'll submit a PR with **Atomic CSS on Steroids**, rather than "Dynamic Atomic CSS library".

@src-code @redonkulus @renatoi @pankajparashar what do you guys think?

**Comment by redonkulus** [comment]
It seems like this project just needs a real project name. Atomizer could just be it, similar to Tachyon or Tailwind. 

Using Atomic CSS in the name is awkward too. Your suggestion also is a little hard to say if asked. "Which CSS project do you use?" "I use Atomic CSS on Steroids." Which doesn't really convey the actual name that well. 

I would just got all in on Atomizer or a new name and change the site to match accordingly.

**Comment by thierryk** [comment]
> > ACSS sounds like it'd just be branding then for Atomizer's particular flavor of Atomic CSS?
> 
> Yes, ACSS would be exactly that. It's Atomic CSS via Atomizer. Atomic CSS is a architecture, ACSS is a "flavor" of the many Atomic CSS implementations we can now find in the wild—and that includes the approach Yahoo! Mail is taking.


**Atomic CSS on Steroids** would not be the name but the *tagline*, the first thing people would see when landing on the home page. The name of the project would be **ACSS**, standing now for *Atomized CSS*.

So it would be more like people saying: "I use ACSS, it's Atomic CSS but on Steroids!"

The changes would be as follow:

   * replace "Atomic CSS" in the "home link" with "ACSS" using a `abbr` with `title` + visually hidden expansion (*Atomized CSS*)
   * replace "Atomic CSS" in the image's `alt` in the "home link" with "ACSS logo"
   * replace "Atomic CSS" in the level 1 heading with "Atomic CSS on Steroids"
   * replace "Atomic CSS" in the image's `alt`inside the level 1 heading with "ACSS logo"

I believe the 3 other occurrences of "Atomic CSS" on the home page do not relate to the project but to the method, so we would not change those. But we would change other occurrences like the ones found in  `<title>`, `<meta>`, etc. (from "Atomic CSS" to "Atomized CSS").

*As a side note*, did anybody run this project locally recently? `npm run dev` does not return any error but `main.css` "loses" the Atomizer stylesheet after any change I make. Is there any known issue that would not be documented? The readme file does not say much ;)

**Comment by thierryk** [comment]
The **Meet Atomizer** section is where we'd try to differentiate "ACSS" from "Atomic CSS" while referring to Atomizer. 

So what about replacing this:

> <p><a href="https://github.com/acss-io/atomizer">Atomizer</a> is a tool for creating Atomic CSS. Generate an Atomic stylesheet dynamically from the Atomic classes you're actually using in your project (no unused styles!), or predeclare styles in configuration - it's up to you. Atomizer is not opinionated, brings no CSS of its own, and integrates nicely with your favorite task runner.</p>

With:

<p>ACSS stands for <em>Atomized CSS</em>. ACSS relies on <a href="https://github.com/acss-io/atomizer">Atomizer</a> to dynamically generate an Atomic stylesheet from the Atomic classes you're actually using in your project (no unused styles!), or predeclare styles in configuration - it's up to you. ACSS is not opinionated, brings no CSS of its own, and integrates nicely with your favorite task runner.</p>

Makes sense?

**Comment by redonkulus** [comment]
These changes make sense to me. Anything to clear up the confusion is good. I'm curious what @src-code will think.

**Comment by thierryk** [comment]
> As a side note, did anybody run this project locally recently? (@src-code @redonkulus @renatoi) npm run dev does not return any error but main.css "loses" the Atomizer stylesheet after any change I make. Is there any known issue that would not be documented? The readme file does not say much ;)

Does anybody know?

**Comment by thierryk** [comment]
@redonkulus @src-code **Thank you guys!** :)
