### ISSUE TITLE
Helpers are not searchable on the reference page

### ISSUE THREAD

**Issue by thierryk** [acss-io/acss-site#121]
See [this comment](https://github.com/acss-io/atomizer/issues/296#issuecomment-311571854) in the Atomizer repo. It shows that the reference page returns `Bdx`, `Bdy`, `Bdt`, `Bdend`, `Bdb`, `Bdstart` but no helper classes like `BdX`, `BdY`, `BdT`, `BdEnd`, `BdB`, and `BdStart`.

**Comment by src-code** [comment]
We should make helpers searchable, which would help disambiguate between Atomic classes such as `Bdy()` and helper classes such as `BdY`.  Helpers should be clearly labeled as such, and should have links back to the documentation for Helpers.

**Comment by src-code** [comment]
I've taken a stab at this.  Here's a screenshot of what they will look like:

![helpers](https://user-images.githubusercontent.com/60631/27710456-a74d48ee-5cd4-11e7-9951-12b8719cae27.jpeg)

We'll display the class, name and a brief description with a link to the Helpers docs.  Atomic and Helpers are grouped under separate sections to make things clear.

**Comment by src-code** [comment]
The description and link will be added to the helpers config in atomizer, BTW.

**Comment by thierryk** [comment]
Looking good. Please make sure that the "more" links give context to SR users, for example:

```html
<a href="...">More <b class="Hidden">about BdEnd</b></a>
```

**Comment by src-code** [comment]
@thierryk Great idea!  Done now!

**Comment by renatoi** [comment]
:shipit: Looks really good!
