### ISSUE TITLE
Landing page should be updated to show atomizer

### ISSUE THREAD

**Issue by renatoi** [acss-io/acss-site#144]
I believe that the landing page of acss.io should change to show the GIF that pretty much sums it all up:

![atomizer-in-action](https://media-exp1.licdn.com/dms/image/C5622AQGXVndFM5zx1w/feedshare-shrink_1280/0/1612641006232?e=1616630400&v=beta&t=Z6DgiAvCNueeOVaiL6RVdkGXMUA_SVk9Hrk_uQvX-vw)

or at least something similar to this + an online editor.

Example that I like: https://svelte.dev/

1. How to install right at the top
2. Online editor at the bottom
3. Show GIF somewhere

Thoughts?

**Comment by redonkulus** [comment]
Love this idea. A picture can say a thousand words.

**Comment by src-code** [comment]
Agree, make it so!
