### ISSUE TITLE
ACSS Renaissance

### ISSUE THREAD

**Issue by renatoi** [acss-io/acss-site#150]
# Bringing ACSS to modern times

## Website

- Refactor the website to use a new framework such as CRA or NextJS and make it look more modern;
- Show who uses ACSS in the landing page;
- Highlight what makes ACSS unique (in comparison to other CSS solutions);
- Show how "Theming" can be supported and show examples;
- Show tons of other examples;
- Reference must contain all properties on the left side similar, organized by categories, similar to Tailwind CSS.
- A must: add a "Quick start" with popular frameworks, possibly with minimal setup/configuration as possible, we'll probably need to create a `npx` command to do this quick setup. At the minimum support: CRA, NextJS, Vue. These need to be first party support and updated often.

## Tool

- Branding: dish the "atomizer" name and rename it to "ACSS", "AtomicCSS", or something better.
- Support CSS variables.
- Add more Helpers, especially for CSS grids. The power of other frameworks lie primarily in this camp.
- Add alternative to use friendlier class names. My vote is to be verbatim with css e.g. `fontSize(20px)`, `height(100%)`, `display(grid)`, `display:(auto)`, `backgroundColor(green)`, `color(red)`, etc.
- Be more intelligent about parsing. Instead of a general regex search in file, we should parse it to an AST and only generate classes for intended class names (`class` in HTML or `className` in React/JS).
- Support runtime class name generation (`CSS in JS`).
- Make TypeScript a first-class citizen;

**Comment by redonkulus** [comment]
Do this and maintain backwards compatibility or have a migration subcommand in the cli! Love all these ideas.

**Comment by lingyan** [comment]
IDE support would be another nice one to have :)

**Comment by redonkulus** [comment]
@renatoi is the renaissance dead?
