### ISSUE TITLE
git clone git@github.com:acss-io/atomizer-examples.git

### ISSUE THREAD

**Issue by b-mi** [acss-io/acss-site#156]
Ends with:

H:\Data\repos\ng>git clone git@github.com:acss-io/atomizer-examples.git
Cloning into 'atomizer-examples'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
----------------

It is really very hard to get informations, how to use the atomic css  in web project.

**Comment by redonkulus** [comment]
Looks like you need to setup SSH keys on your computer and add them to your GitHub profile to clone properly. Try these links from GitHub for more help. 

https://docs.github.com/en/authentication/connecting-to-github-with-ssh

https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
