### ISSUE TITLE
[RFC] Rebrand site to Atomizer

### ISSUE THREAD

**Issue by redonkulus** [acss-io/acss-site#170]
@src-code @snyamathi @thierryk @renatoi 

As I've been doing some cleaning up of the Atomic site, one thing that has sort of bothered me is the "Atomic CSS" branding. The site is really not about the generic Atomic CSS architecture but rather about the implementation, i.e, Atomizer. The examples, references and most of the docs are just explaining the custom Atomic CSS implementation created with atomizer.

To reduce confusion, I suggest we make the following changes:

- Site title: Atomizer
- Site description: Atomic CSS utility for modern websites ... (just one suggestion)
- URL: Keep the same, acss.io is short and sweet, plus migrating domains is a pain and costs money
- Remove references to "Atomic CSS on Steroids". Steroids has a negative connotation and seems a bit heavy handed as a tagline for a library.

I'm open to other suggestions but wanted to open this up for discussion.

**Comment by thierryk** [comment]
I agree that the "branding" should evolve, as it did once already.

If you recall, the `title` for the ACSS abbreviation used to say "Atomic CSS", now it says "**Atomized** CSS".
The `h1` used to be "Atomic CSS", now it is "Atomic CSS *on Steroids*".
 
This was done to "emphasis" the use of **Atomizer** at a time when Atomic CSS had became mainstream but when everybody were still relying on "static" files. This is no longer true though, so I agree with you that we should make the web site more about the tool (Atomizer) and less about the architecture (Atomic CSS). 

My thoughts on your bullet points...

* Site title: Atomizer

`<title>Atomizer</title>` would be better than what we have now `<title>ACSS</title>`

* Site description: Atomic CSS utility for modern websites ... (just one suggestion)

I notice there is no `<meta name="description" ...>` on the web site. For that, Google uses the paragraph below "*Meet Atomizer*":

> ACSS stands for Atomized CSS. ACSS relies on Atomizer to dynamically generate an Atomic stylesheet from the ACSS classes you're actually using in your ...

So it could be just a matter of editing that bit? May be saying:  

> Atomizer is a utility for modern web sites. Atomizer generates an Atomic stylesheet from the ACSS classes you're actually using in your ...

* URL: Keep the same, acss.io is short and sweet, plus migrating domains is a pain and costs money

Definitely!

* Remove references to "Atomic CSS on Steroids". Steroids has a negative connotation and seems a bit heavy handed as a tagline for a library.

That's in the `<h1>` so it'd be great to keep "Atomic CSS" in there. What about saying "Atomic CSS by Atomizer" or something like that? 

Also, I think it could be good to say something about how Atomizer is used on large scale web sites or something (i.e. _Atomizer produces styles sheets serve to million people!_), so devs who discover it don't think it's not "battle tested" and not a good fit for any serious project. 

As a side note, if you edit those pages, what about adding testimonials?

**Comment by thierryk** [comment]
> Do we have testimonials from devs?

I did a quick search on Twitter and found these:

* An [article](https://engineering.wingify.com/posts/shift-to-atomic-css/) by Kushagra Gour
* A [tweet](https://twitter.com/roderickhsiao/status/922620291527852032) from Roderick
* An [article](https://medium.com/@roderickhsiao/building-tinder-online-a447e6c0265e#---0-386) from Roderick
* Another [tweet](https://twitter.com/f_abeni/status/868178233661018113)

I'm sure we could get more results and then ask authors to write something or pick a sentence or 2 from their articles or tweets(?), but I'm not sure testimonials are "important" enough to justify the extra effort...

**Comment by redonkulus** [comment]
We can do that in a follow up PR.

@thierryk I see references to "ACSS classes" everywhere, should that be changed to "Atomizer classes"?

**Comment by thierryk** [comment]
Since *ACSS* now stands for "Atomized CSS" I think "ACSS classes" works but "Atomizer classes" would work as well.
The latter may be better in term of SEO though, as it increases the occurence of the "Atomizer" keyword through the site (I don't think "ACSS" as much value) but I don't really have a preference beside that; let see if @src-code, @snyamathi, and @renatoi have one.

**Comment by redonkulus** [comment]
@thierryk here you go https://github.com/acss-io/acss-site/pull/171 ... working on getting some preview environment setup
